#!/usr/bin/env bash
#set -o xtrace
#set -o errexit


# packages
install_os_packages() {
    local \
        os_packages
    os_packages=("${@}")
    sudo apt-get install "${os_packages[@]}"
}


setup_git_options() {
    local \
        item \
        opt \
        val \
        git_options
    git_options=("${@}")
    for item in "${git_options[@]}"; do
      opt="${item%=*}"
      val="${item##*=}"
      git config --global "${opt}" "${val}"
    done
}

setup_bashit() {
    # bashit
    ! [[ -d "${HOME}/.bash_it" ]] && git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
    source "${HOME}/.bashrc"
}


setup_virtualenv() {
    local \
        python_packages \
        ve
    python_packages="${1}"
    if ! [[ -r "${python_packages}" ]]; then
        echo "FATAL: ${python_packages} is not present in ${PWD}"
        exit 1
    fi
    ve="$( sha1sum "${python_packages}" | cut -d' ' -f1)"
    if ! [[ -d "${WORKON_HOME}/${ve}" ]]; then
        mkvirtualenv "${ve}" -r "${python_packages}"
    fi
    workon "${ve}"
    echo "Using virtualenv: ${ve}"
}


setup_pathogen() {
    # pathogen
    mkdir -p ~/.vim/autoload ~/.vim/bundle
    ! [[ -r "${HOME}/.vim/autoload/pathogen.vim" ]] \
    && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

    if [[ -r "${HOME}/.vimrc" ]]; then
        mv "${HOME}/.vimrc" "${HOME}/.vimrc.$(date +%s)"
    fi
    cat > ~/.vimrc << _EOF1
# Autogenerated by $0 on $( date )
execute pathogen#infect()
syntax on
filetype plugin indent on
set tabstop=4 shiftwidth=4 expandtab
_EOF1
}

install_pathogen_packages(){
    local \
        pkg \
        repo \
        src \
        dst \
        pathogen_packages
    pathogen_packages=("${@}")
    for pkg in "${pathogen_packages[@]}"; do
        repo="${pkg##*/}"
        repo="${repo%.*}"
        src="https://github.com/${pkg}"
        dst="${HOME}/.vim/bundle/${repo}"
        if [[ -d "${dst}" ]]; then
            continue
        fi
        git clone "${src}" "${dst}"
    done
    # enable pathogen and use packages:
    cat > ~/.vimrc << _EOF
execute pathogen#infect()
syntax on
filetype plugin indent on

set tabstop=4 shiftwidth=4 expandtab

map <silent> <F3> :set invnumber<cr>
map <silent> <F4> :NERDTreeToggle<CR>

_EOF

}


main() {
    local \
        os_packages \
        pathogen_packages \
        git_options \
        python_packages

    os_packages=($(cat os_requirements.txt))
    install_os_packages "${os_packages[@]}"
    git_options=($(cat git_options.txt))
    setup_git_options "${git_options[@]}"
    setup_bashit
    python_packages="requirements.txt"
    setup_virtualenv "${python_packages}"
    setup_pathogen
    pathogen_packages=($(cat pathogen_packages.txt))
    install_pathogen_packages "${pathogen_packages[@]}"
}


main "${@}"
